//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neighborly_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public string MessageContent { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int TaskID { get; set; }
    
        public virtual Task2 Task2 { get; set; }
    }
}
